myapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todolist/', include('todolist.urls')),
    path('user/', include('user.urls')),
]

todolist/urls.py
from django.urls import path
from . import views

app_name = 'todolist'

urlpatterns = [
    # 인덱스페이지
    path('', views.Index.as_view(), name='index'),
    # 리스트 페이지
    path('list/', views.TodoList.as_view(), name='todo'),
    path('list/<int:category_id>', views.TodoList.as_view(), name='todo-detail'),
    # 카테고리
    path('list/category/write', views.CategoryWrite.as_view(), name='category-write'),
    path('list/<int:category_id>/delete', views.CategoryDelete.as_view(), name='category-delete'),
    path('list/<int:category_id>/update', views.CategoryUpdate.as_view(), name='category-update'),
    # 할일
    path('list/<int:category_id>/todo/write', views.TodoWrite.as_view(), name='todo-write'),
    path('list/todo/<int:todo_id>/delete', views.TodoDelete.as_view(), name='todo-delete'),
    path('list/todo/<int:todo_id>/update', views.TodoUpdate.as_view(), name='todo-update'),
    path('list/todo/<int:todo_id>/toggle', views.TodoClearToggle.as_view(), name='todo-toggle'),
]

user/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'user'

urlpatterns = [
    path("login/", views.CustomLogin.as_view(), name='login'),
    path("logout/", LogoutView.as_view(next_page="todolist:index"), name='logout'),
    path("signup/", views.SignUp.as_view(), name='signup'),
]

todolist/models.py
from django.db import models
from user.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=15)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user} - {self.name}'


class Todo(models.Model):
    title = models.CharField(max_length=15)
    content = models.TextField()
    is_clear = models.BooleanField(default=False)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.category} - {self.title}'

todolist/forms.py
from django import forms
from .models import Category, Todo


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = ['name']


class TodoForm(forms.ModelForm):

    class Meta:
        model = Todo
        fields = ['title', 'content']

todolist/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseForbidden

from .models import Category, Todo
from .forms import CategoryForm, TodoForm


# Create your views here.
### 유저 정보 확인
def userValidate(user, data_user):
    return user == data_user
    # return HttpResponseForbidden()


### 인덱스 페이지
class Index(View):

    def get(self, request):
        if request.user.is_authenticated:
            return redirect('todolist:todo')
        return render(request, 'todolist/index.html')


### 리스트 페이지
class TodoList(LoginRequiredMixin, View):

    def get(self, request, category_id=None):
        user = request.user
        categories = Category.objects.filter(user=user)[::-1]
        if categories:
            if category_id is None:
                category_id = categories[0].pk
            category_user = Category.objects.get(pk=category_id).user
            if not userValidate(user, category_user):
                redirect('todolist:todo')
            todos = Todo.objects.filter(category=category_id)[::-1]
        else:
            todos = {}

        context = {
            'categories': categories,
            'todos': todos,
            'category_id': category_id,
        }

        return render(request, 'todolist/todo.html', context)


### 카테고리 CRUD
class CategoryWrite(View):

    def post(self, request):
        form = CategoryForm(request.POST)
        if form.is_valid():
            user = request.user
            name = form.cleaned_data['name']
            category = Category.objects.create(name=name, user=user)
            return redirect('todolist:todo-detail', category_id=category.pk)


class CategoryDelete(View):

    def post(self, request, category_id):
        category = Category.objects.get(pk=category_id)
        if userValidate(request.user, category.user):
            category.delete()
            return redirect('todolist:todo')


class CategoryUpdate(View):

    def post(self, request, category_id):
        form = CategoryForm(request.POST)
        category = Category.objects.get(pk=category_id)
        if form.is_valid() and userValidate(request.user, category.user):
            name = form.cleaned_data['name']
            category.name = name
            category.save()
            # return JsonResponse({'category_update': True})
            return redirect('todolist:todo-detail', category_id=category_id)


### 할일 CRUD
class TodoWrite(View):

    def post(self, request, category_id):
        form = TodoForm(request.POST)
        category = Category.objects.get(pk=category_id)
        if form.is_valid() and userValidate(request.user, category.user):
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            todo = Todo.objects.create(title=title, content=content, category=category)
            return redirect('todolist:todo-detail', category_id=category_id)


class TodoDelete(View):

    def post(self, request, todo_id):
        todo = Todo.objects.get(pk=todo_id)
        if userValidate(request.user, todo.category.user):
            category_id = todo.category.id
            todo.delete()
            return redirect('todolist:todo-detail', category_id=category_id)


class TodoClearToggle(View):

    def post(self, request, todo_id):
        todo = Todo.objects.get(pk=todo_id)

        if userValidate(request.user, todo.category.user):
            todo.is_clear = not todo.is_clear
            todo.save()
            return JsonResponse({'is_clear': todo.is_clear})


class TodoUpdate(View):

    def post(self, request, todo_id):
        form = TodoForm(request.POST)
        todo = Todo.objects.get(pk=todo_id)
        if form.is_valid() and userValidate(request.user, todo.category.user):
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            category_id = todo.category.id
            todo.title = title
            todo.content = content
            todo.save()
            # return JsonResponse({'todo_update': True})
            return redirect('todolist:todo-detail', category_id=category_id)

todolist/templates/todolist/index.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" href="{% static '/css/index.css' %}">
{% endblock head %}
{% block body %}
  <main>
    <section class="index-section">
      <div class="index-subtitle">
        <h2>여러분의 Todo List를 관리하세요.</h2>
        <div class="index-linkwrap">
          <a href="{% url 'user:login' %}">로그인하기</a>
          <a href="{% url 'user:signup' %}">시도해보기</a>
        </div>  
      </div>
      <div class="index-description">
      </div>
    </section>
  </main>
{% endblock body %}

todolist/templates/todolist/todo.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" href="{% static '/css/todo.css' %}">
{% endblock head %}
{% block body %}
  <main class="todo-main">
    <nav class="todo-category">
      <div class="category-title">
        <h2>Todo Categories</h2>
      </div>
      <form action="{% url 'todolist:category-write' %}" method="post" class="category-add">
        {% csrf_token %}
        <input type="text" id="category-input" name="name" required maxlength="15"/>
        <button type="submit" class="category-addbtn">&#43;</button>
      </form>
        <div class="category-list">
        {% if categories %}
          {% for category in categories %}
            {% if category.pk == category_id %}
            <div class="category show">
            {% else %}
            <div class="category">
            {% endif %}
              <form action="{% url 'todolist:todo-detail' category_id=category.pk %}" method="get">
                <button type="submit" class="category-select" category="{{category.pk}}">{{category.name}}</button>
              </form>
              <div class="category-btnwrap">
                <form action="{% url 'todolist:category-update' category_id=category.pk %}" method="post">
                  <input type="hidden" id="category-update" name="name" required maxlength="15" />
                  <button type="button" class="category-update">&#9998;</button>
                  {% csrf_token %}
                </form>
                <form action="{% url 'todolist:category-delete' category_id=category.pk %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="category-delete" category="{{category.pk}}">&#215;</button>
                </form>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <p>카테고리가 없습니다.</p>
        {% endif %}
        </div>
    </nav>
    <section class="todo-list">
      {% if todos %}
        {% for todo in todos %}
        {% if todo.is_clear %}
        <div class="todo-box clear">
          <input type="checkbox" class="todo-toggle" action="{% url 'todolist:todo-toggle' todo_id=todo.pk %}" checked>
        {% else %}
        <div class="todo-box">
          <input type="checkbox" class="todo-toggle" action="{% url 'todolist:todo-toggle' todo_id=todo.pk %}">
        {% endif %}
          <h3 class="todo-title">{{todo.title}}</h3>
          <p class="todo-content">{{todo.content}}</p>
          <button type="button" class="todo-update todo-button" action="{% url 'todolist:todo-update' todo_id=todo.pk %}">&#9998;</button>
          <form action="{% url 'todolist:todo-delete' todo_id=todo.pk %}" method="post" class="todo-button">
            {% csrf_token %}
            <button type="submit" class="todo-delete">&#215;</button>
          </form>
        </div>
        {% endfor %}
        <button type="button" class="show-editor">+</button>
      {% else %}
        {% if category_id %}
          <div class="todo-box">할 일이 없습니다.</div>
          <button type="button" class="show-editor">+</button>
        {% else %}
          <div class="todo-box">카테고리를 생성해주세요.</div>
        {% endif %}
      {% endif %}
    </section>
    {% if category_id %}
    <form class="todo-editor" action="{% url 'todolist:todo-write' category_id=category_id %}" method="post">
      <div class="editor-wrap">
        <label for="editor-title">제목</label>
        <input 
              type="text" 
              name="title" 
              id="editor-title" 
              class="editor-title" 
              maxlength="15"
              required
        />
        <label for="editor-content">내용</label>
        <textarea class="editor-content" name="content" id="editor-content" required></textarea>
        <div class="editor-buttonbox">
          <button type="button" class="editor-cancle">취소</button>
          <button type="submit" class="editor-submit">완료</button>
        </div>
      </div>
      {% csrf_token %}
      </form>
    {% endif %}
  </main>
{% endblock body %}
{% block js %}
  <script>
    const API = (url, data = null) => {
      const body = new FormData()
      if (data) {
        for (const name in data){
          body.append(name, data[name])
        }
      }
      fetch(url,{
        method: "post",
        headers: {
            "X-CSRFToken": "{{ csrf_token }}"
        },
            redirect: "follow",
            body: body,
        });
      }
    
    if ("{{ category_id }}" !== "None") {
      const todoEditor = document.querySelector(".todo-editor");
      const showEditorBtn = document.querySelector(".show-editor");
      const closeEditorBtn = document.querySelector(".editor-cancle");
      const todoToggleBtn = document.querySelectorAll(".todo-toggle");
      const todoUpdateBtn = document.querySelectorAll(".todo-update");
      const editorInput = todoEditor.querySelector(".editor-title");
      const editorTextarea = todoEditor.querySelector(".editor-content");

      const editorAPIUrl = todoEditor.getAttribute("action")

      const editorToggle = () => {
          todoEditor.classList.toggle("show");
          if (todoEditor.classList.contains("show")){
              todoEditor.querySelector("input").focus();
          }
      }
      showEditorBtn.addEventListener("click", () => {
        todoEditor.setAttribute("action", editorAPIUrl);
        editorInput.value = "";
        editorTextarea.value = "";
        editorToggle();
      })

      closeEditorBtn.addEventListener("click", () => {
         editorToggle();
      })

      todoToggleBtn.forEach((checkBox) => {
      const box = checkBox.parentElement;
      const url = checkBox.getAttribute("action");
      checkBox.addEventListener("change", () => {
        API(url);
        box.classList.toggle("clear");
        })
      })

      todoUpdateBtn.forEach((btn) => {
        const url = btn.getAttribute("action");
        const todoBox = btn.parentElement
        const title = todoBox.querySelector(".todo-title")
        const content = todoBox.querySelector(".todo-content")
        btn.addEventListener("click", ()=>{
          todoEditor.setAttribute("action", url);
          editorInput.value = title.innerText;
          editorTextarea.value = content.innerText;
          editorToggle();
        })
      })      
    }

    const categoryUpdateBtn = document.querySelectorAll(".category-update");

    categoryUpdateBtn.forEach((btn) => {
      const form = btn.parentElement;
      const input = form.querySelector("input");
      const category = form.parentElement.parentElement.querySelector(".category-select");
      btn.addEventListener("click", () => {
        if (input.value) {
          const url = form.getAttribute("action");
          API(url, data = {name: input.value});
          category.innerText = input.value;
          input.setAttribute("type", "hidden");
          input.value = "";
        }
        else {
          input.setAttribute("type", "text");
          input.value = category.innerText;
          input.focus();
        }
      })
    })
  </script>
{# <script src="{% static '/js/todo.js' %}" type="module"></script> #}
{% endblock js %}
</body>
</html>